#!/bin/bash

# Handle ssh configuration
mkdir -p /root/.ssh
if [ -e /ssh_config ] ; then
    cp /ssh_config /root/.ssh/config
fi

if [ -e /known_hosts ] ; then
    cp /known_hosts /root/.ssh/
fi

if [ -e /id_rsa ] ; then
    cp /id_rsa /root/.ssh/
fi

chown -R root:root /root/.ssh
chmod -R u=rwX,g=,o= /root/.ssh

if [ -n "SSHFS" ] ; then
    mkdir -p /sshfs
    if ! sshfs "$SSHFS" /sshfs ; then
        echo "Failed to mount sshfs: $SSHFS" >&2
        exit 1
    fi
fi

exec /usr/local/bin/attic "$@"
