#!/bin/bash

# Make sure that the locale is set up if specified
if [ -n "$LANG" ] ; then
    locale-gen "$LANG"
fi

if [ -n "$LC_ALL" ] && [ "$LC_ALL" != "$LANG" ] ; then
    locale-gen "$LC_ALL"
fi

# Handle ssh configuration
mkdir -p /root/.ssh
if [ -e /ssh_config ] ; then
    cp /ssh_config /root/.ssh/config
fi

if [ -e /known_hosts ] ; then
    cp /known_hosts /root/.ssh/
fi

if [ -e /id_rsa ] ; then
    cp /id_rsa /root/.ssh/
fi

chown -R root:root /root/.ssh
chmod -R u=rwX,g=,o= /root/.ssh

if [ -n "$SSHFS" ] ; then
    mkdir -p /sshfs

    sshfscmd=("/usr/bin/sshfs" "$SSHFS" /sshfs)
    if [ -n "SSHFAST" ] ; then
        sshfscmd+=(-o "Ciphers=arcfour")
    fi

    if [ -n "$SSHOPTS"] ; then
        for opt in $SSHOPTS ; do
            sshfscmd+=(-o "$opt")
        done
    fi

    if ! "${sshfscmd[@]}" ; then
        echo "Failed to mount sshfs: $SSHFS" >&2
        exit 1
    fi
fi

exec /usr/local/bin/attic "$@"
